spring:
  datasource:
#    url: jdbc:postgresql://localhost:26257/demo
    url: jdbc:postgresql://localhost:5432/demo
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
server:
  port: 8082

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO