spring:
  datasource:
    url: jdbc:postgresql://cockroachdb-public:26257/demo
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
server:
  port: 8081
